Chat/d09/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

Chat/d09/chat/urls.py
from django.urls import path

from chat.views import *

app_name = "chat"

urlpatterns = [
    path("<str:room_name>/", room_view, name="room"),
    path("", index_view, name="index"),
]

Chat/d09/d09/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda request: redirect('account/', permanent=True)),
    path('account/', include('account.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

Chat/d09/account/models.py
from django.db import models

# Create your models here.

Chat/d09/chat/models.py
from django.db import models
import django.contrib.auth as auth


class ChatRoom(models.Model):
  name = models.CharField(max_length=30, unique=True)
  users = models.ManyToManyField(auth.get_user_model(), related_name="rooms")

  def __str__(self):
    return self.name


class ChatMessage(models.Model):
  room = models.ForeignKey(ChatRoom, verbose_name="room", on_delete=models.CASCADE)
  user = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
  content = models.TextField()
  timestamp = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.content
  
  @classmethod
  def get_last_3_msg(cls, room):
    return cls.objects.filter(room=room).order_by("-timestamp")[:3][::-1]

Chat/d09/account/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_exempt


def index_view(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == 'GET':
        return JsonResponse({
            'success': True,
            'is_authenticated': request.user.is_authenticated,
            'username': request.user.username
        })
    context = {
        'is_authenticated': request.user.is_authenticated,
        'username': request.user.username if request.user.is_authenticated else '',
    }
    return render(request, 'account.html', context)

@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'error': form.errors.as_json()})
    return JsonResponse({'success': False, 'error': 'Invalid request'})

@csrf_exempt
@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'Invalid request'})

Chat/d09/chat/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib import messages


@login_required
def index_view(request):
  rooms = ChatRoom.objects.all().order_by("name")
  return render(request, "index.html", { "rooms": rooms })


@login_required
def room_view(request, room_name):
  try:
    room = ChatRoom.objects.get(name=room_name)
  except ChatRoom.DoesNotExist:
    messages.error(request, "The chat room does not exist.")
    return redirect("chat:index")
  return render(request, "room.html", { "room": room })

Chat/d09/chat/templates/index.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>DO9 - Account</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	{% bootstrap_css %}
	<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</head>
<body>
	<div class="navbar navbar-light bg-light">
		<div class="container-fluid d-flex justify-content-between align-items-center position-relative">
			<a class="navbar-brand" href="{% url 'account:index' %}">D09</a>
			<div id="logout-btn-navbar" class="ml-auto position-relative">
				<button type="button" id="logout-btn" class="btn btn-outline-secondary">Logout</button>
			</div>
		</div>
	</div>

	{% if messages %}
		<div class="container mt-4">
			<div class="alert alert-warning">
				{% for message in messages %}
					<p class="m-2">{{ message }}</p>
				{% endfor %}
			</div>
		</div>
	{% endif %}

	{% if rooms %}
		<div class="conatiner">
			<div class="row justify-content-center">
				<div class="col-md-8">
					<br>
					<h1 class="my-5 text-center">Available Chat Rooms</h1>
					<br>
					<div class="list-group">
						{% for room in rooms %}
							<a href="{% url "chat:room" room.name %}" class="list-group-item list-group-item-action">{{ room.name }}</a>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	{% endif %}

	{% bootstrap_javascript %}
	<script src="{% static 'js/index.js' %}"></script>
  <script>
    var loginUrl = "{% url 'account:index' %}"
		var logoutUrl = "{% url 'account:logout' %}"
		var wsUrl = 'ws://' + window.location.host + '/chat'
	</script>

</body>
</html>

Chat/d09/chat/templates/room.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Chat room {{ room.name }}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	{% bootstrap_css %}
	<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href={% static "css/chat.css" %}>
</head>
<body>
	<div class="navbar navbar-light bg-light">
		<div class="container-fluid d-flex justify-content-between align-items-center position-relative">
			<a class="navbar-brand" href="{% url 'account:index' %}">D09</a>
			<div id="logout-btn-navbar" class="ml-auto position-relative">
				<button type="button" id="logout-btn" class="btn btn-outline-secondary">Logout</button>
			</div>
		</div>
	</div>

	{% if messages %}
		<div class="container mt-4">
			<div class="alert alert-warning">
				{% for message in messages %}
					<p class="m-2">{{ message }}</p>
				{% endfor %}
			</div>
		</div>
	{% endif %}

  <div class="m-5 d-flex justify-content-center">
    <h1>{{ room.name }}</h1>
  </div>
	
	<div class="row">
		<div class="ms-3 col-3">
			<div id="hat-container">
				<h5>Connected users</h5>
				<ul id="user-table" class="list-group"></ul>
			</div>
		</div>

		<div class="col-6">
			<div id="chat-container">
				<div id="chat-messages"></div>
				<div class="mt-3">
					<div class="input-group">
						<input
							type="text" 
							id="message-input" 
							class="form-control" 
							placeholder="Type your message..."
						>
						<button id="send-button" class="btn btn-primary">Send</button>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% bootstrap_javascript %}
	<script src="{% static 'js/chat.js' %}"></script>
  <script>
    var loginUrl = "{% url 'account:index' %}";
		var logoutUrl = "{% url 'account:logout' %}";
		var wsUrl = "ws://" + window.location.host + "/ws/chat/{{ room.name }}/";
    var username = "{{ request.user.username }}";
	</script>

</body>

</html>